### ISSUE TITLE
Add Docker to Image

### ISSUE THREAD

**Issue by cancan101** [aws/aws-parallelcluster-cookbook#1]
For Centos: https://docs.docker.com/installation/centos/
Including:

```
sudo usermod -aG docker ec2-user
```

**Comment by dougalb** [comment]
To clarify, you would like to see Docker support added to the CfnCluster builds?

**Comment by cancan101** [comment]
Yes, a cookbook for a compute node with the docker daemon set up such that jobs submitted can use docker.

**Comment by enrico-usai** [comment]
Hi @cancan101 , since aws-parallelcluster 2.0.0 you can [build your custom AMI](https://aws-parallelcluster.readthedocs.io/en/latest/ami_customization.html?highlight=create%20ami) or use a [pre/post install script](https://aws-parallelcluster.readthedocs.io/en/latest/pre_post_install.html).
